-- AlterTable
ALTER TABLE `orders` MODIFY `status` ENUM('PENDING_CONFIRMATION', 'WAITING_PAYMENT', 'WAITING_CUSTOMER_ESTIMATION_CONFIRMATION', 'WAITING_SHOP_CONFIRMATION', 'PROCESSING', 'COMPLETED', 'REJECTED', 'PAYMENT_REJECTED', 'CANCELLED') NOT NULL;

-- AddForeignKey
ALTER TABLE `shop_carts` ADD CONSTRAINT `shop_carts_cart_id_fkey` FOREIGN KEY (`cart_id`) REFERENCES `carts`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
