-- AlterTable
ALTER TABLE `orders` MODIFY `status` ENUM('PENDING_CONFIRMATION', 'WAITING_PAYMENT', 'WAITING_CUSTOMER_ESTIMATION_CONFIRMATION', 'WAITING_SHOP_CONFIRMATION', 'PROCESSING', 'COMPLETED', 'REJECTED', 'PAYMENT_REJECTED', 'ESTIMATION_REJECTED', 'CANCELLED') NOT NULL;
